### ISSUE TITLE
Adding other execs to the AppImage

### ISSUE THREAD

**Issue by mryndzionek** [mryndzionek/composable-sdr#2]
As suggested by @alphafox02

**Comment by mryndzionek** [comment]
First attempt: e54cbceb67473cf80f0a4252024b797681ce8ae2

**Comment by mryndzionek** [comment]
I've also triggered a build. The AppImage can be downloaded [here](https://github.com/mryndzionek/composable-sdr/actions/runs/146292074). In order to choose the exec to run, one must create a symbolic link named after the exec, so for helidecode:
```sh
ln -s Soapy_SDR-x86_64.AppImage helidecode
./helidecode output.f32
```

**Comment by alphafox02** [comment]
Excellent, hope to give this a try late tonight with the helidecode. If it helps any, I have a hackrf, rtlsdr, and sdrplay hardware I can test against additional soapy modules. For sdrplay I use this,

https://github.com/SDRplay/SoapySDRPlay

And it also requires the newer 3.x api which I do have preinstalled in DragonOS but just in case Incase must be bundled in you can find it here under the x86 tab

http://www.sdrplay.com/downloads/

Note that is says 3.06 api but it’s actually 3.07.

**Comment by mryndzionek** [comment]
I've managed to integrate SDRPlay support into the build. Test AppImage is [here](https://github.com/mryndzionek/composable-sdr/actions/runs/146607302).

**Comment by alphafox02** [comment]
Excellent. I will test tonight. The SDRplay people will be happy to see it working I’m sure. I have an rsp1a and rsp2duo.

**Comment by alphafox02** [comment]
Results so far,

SoapySDRUtil --find
######################################################
##     Soapy SDR -- the SDR abstraction library     ##
######################################################

linux; GNU C++ version 7.3.0; Boost_106501; UHD_003.010.003.000-0-unknown

Found device 0
  default_input = True
  default_output = True
  device_id = 0
  driver = audio
  label = PulseAudio

Found device 1
  driver = sdrplay
  label = SDRplay Dev0 RSP1A 19110B8997

dragon@dragon:~/Downloads$ ./Soapy_SDR-x86_64.AppImage --devname sdrplay
No SDR devices detected
Unable to open source: ISoapy (SoapySDRInputCfg {_devname = "sdrplay", _frequency = 1.0e8, _gain = 0.0})

I'll continue to troubleshoot.

**Comment by alphafox02** [comment]
> I've also triggered a build. The AppImage can be downloaded [here](https://github.com/mryndzionek/composable-sdr/actions/runs/146292074). In order to choose the exec to run, one must create a symbolic link named after the exec, so for helidecode:
> 
> ```shell
> ln -s Soapy_SDR-x86_64.AppImage helidecode
> ./helidecode output.f32
> ```

Worked perfectly. I had to pull down the latest YouTube-dl and audacity before I could follow along. End result was the kml just like your example and gpsprune opened it up.

**Comment by mryndzionek** [comment]
I've glanced through the diff in the morning and noticed one thing missing. Fixed that. New build is [here](https://github.com/mryndzionek/composable-sdr/actions/runs/147073740).

**Comment by alphafox02** [comment]
Looks like it may be working now. I'll do some more tests asap and see if me having to restart the sdrplay service was just a glitch. I had just booted up the computer with the RSP1A already plugged in. Downloaded your latest build, unzipped it, chmod + x, and ran the following. An output.cf32 was generated. 

./Soapy_SDR-x86_64.AppImage --devname sdrplay
Available devices: ["sdrplay"]
Using device: sdrplay
[INFO] devIdx: 0
[INFO] hwVer: 255
[INFO] Using format CF32.
Using DC blocker:
iir filter [normal]:
  b :  1.00000000 -1.00000000
  a :  1.00000000 -0.99949998
[ERROR] ReleaseDevice Error: sdrplay_api_ServiceNotResponding
terminate called after throwing an instance of 'std::runtime_error'
  what():  ReleaseDevice() failed
Aborted (core dumped)
dragon@dragon:~/Downloads$ sudo service sdrplay restart
dragon@dragon:~/Downloads$ ./Soapy_SDR-x86_64.AppImage --devname sdrplay
Available devices: ["sdrplay"]
Using device: sdrplay
[INFO] devIdx: 0
[INFO] hwVer: 255
[INFO] Using format CF32.
Using DC blocker:
iir filter [normal]:
  b :  1.00000000 -1.00000000
  a :  1.00000000 -0.99949998
dragon@dragon:~/Downloads$

**Comment by alphafox02** [comment]
Your example #1 worked perfectly with the sdrplay RSP1A. I'll test again with the RSPDuo, but I expect the same results. Both devices have up to 10MHz wide bandwidth and are both great pieces of equipment. 

For your example number 2, I have a FRS radio with 22 channels in the 462/467MHz range. If I adjust settings accordingly and transmit with audio on one of the channels should I expect to capture that with a -c 22? If this is off topic for this thread just let me know. Figured I'd test other options with the sdrplay equipment, like AGC.
 
https://fccid.io/2AHJMACXAH

**Comment by mryndzionek** [comment]
> For your example number 2, I have a FRS radio with 22 channels in the 462/467MHz range. If I adjust settings accordingly and transmit with audio on one of the channels should I expect to capture that with a -c 22?

Yes, if the modulation is FM then I think it should work.

**Comment by probonopd** [comment]
Could it be scripted to automatically detach the kernel driver when launched so that it "just works" to execute the AppImage?

```
# dmesg for information

[15554.135335] usb 9-2.1.3: new high-speed USB device number 11 using xhci_hcd
[15554.260666] usb 9-2.1.3: New USB device found, idVendor=0bda, idProduct=2838, bcdDevice= 1.00
[15554.260668] usb 9-2.1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[15554.260670] usb 9-2.1.3: Product: RTL2838UHIDIR
[15554.260672] usb 9-2.1.3: Manufacturer: Realtek
[15554.260674] usb 9-2.1.3: SerialNumber: 00000001
[15554.272285] usb 9-2.1.3: dvb_usb_v2: found a 'Realtek RTL2832U reference design' in warm state
[15554.341390] usb 9-2.1.3: dvb_usb_v2: will pass the complete MPEG2 transport stream to the software demuxer
[15554.341401] dvbdev: DVB: registering new adapter (Realtek RTL2832U reference design)
[15554.341404] usb 9-2.1.3: media controller created
[15554.341935] dvbdev: dvb_create_media_entity: media entity 'dvb-demux' registered.
[15554.344376] i2c i2c-3: Added multiplexed i2c bus 4
[15554.344379] rtl2832 3-0010: Realtek RTL2832 successfully attached
[15554.344394] usb 9-2.1.3: DVB: registering adapter 0 frontend 0 (Realtek RTL2832 (DVB-T))...
[15554.344398] dvbdev: dvb_create_media_entity: media entity 'Realtek RTL2832 (DVB-T)' registered.
[15554.344573] r820t 4-001a: creating new instance
[15554.352014] r820t 4-001a: Rafael Micro r820t successfully identified
[15554.353479] rtl2832_sdr rtl2832_sdr.2.auto: Registered as swradio0
[15554.353480] rtl2832_sdr rtl2832_sdr.2.auto: Realtek RTL2832 SDR attached
[15554.353482] rtl2832_sdr rtl2832_sdr.2.auto: SDR API is still slightly experimental and functionality changes may follow
[15554.361141] Registered IR keymap rc-empty
[15554.361175] rc rc0: Realtek RTL2832U reference design as /devices/pci0000:00/0000:00:1c.1/0000:03:00.0/usb9/9-2/9-2.1/9-2.1.3/rc/rc0
[15554.361227] input: Realtek RTL2832U reference design as /devices/pci0000:00/0000:00:1c.1/0000:03:00.0/usb9/9-2/9-2.1/9-2.1.3/rc/rc0/input18
[15554.361369] rc rc0: lirc_dev: driver dvb_usb_rtl28xxu registered at minor = 0, raw IR receiver, no transmitter
[15554.361405] usb 9-2.1.3: dvb_usb_v2: schedule remote query interval to 200 msecs
[15554.375256] usb 9-2.1.3: dvb_usb_v2: 'Realtek RTL2832U reference design' successfully initialized and connected

# Now trying to execute the AppImage

me@host:~$ sudo '/home/me/Downloads/Soapy_SDR-x86_64.AppImage (2)'
shm_open: No such file or directory
[ERROR] sdrplay_api_Open() Error: sdrplay_api_Fail
[ERROR] Please check the sdrplay_api service to make sure it is up. If it is up, please restart it.

Kernel driver is active, or device is claimed by second instance of librtlsdr.
In the first case, please either detach or blacklist the kernel module
(dvb_usb_rtl28xxu), or enable automatic detaching at compile time.

usb_claim_interface error -6
[ERROR] SoapySDR::Device::enumerate(sdrplay) sdrplay_api_Open() failed
Available devices: ["rtlsdr"]
Using device: rtlsdr

Kernel driver is active, or device is claimed by second instance of librtlsdr.
In the first case, please either detach or blacklist the kernel module
(dvb_usb_rtl28xxu), or enable automatic detaching at compile time.

usb_claim_interface error -6
[INFO] Using format CF32.
Using DC blocker:
iir filter [normal]:
  b :  1.00000000 -1.00000000
  a :  1.00000000 -0.99949998
```

**Comment by alphafox02** [comment]
I’m not experiencing the problem you’re having with kernel drivers etc. Do you have another instance of librtlsdr already installed? I have the packaged version for 18.04 installed and when I run the app image with either rtlsdr or sdrplay it just works, except having to maybe restart the sdrplay service that’s installed outside of the app image. 

I’ll keep testing and see if I can replicate you’re experience.

**Comment by mryndzionek** [comment]
I'm also not having this problem. I think I had to do this on Ubuntu. Now I'm on Mint.

**Comment by probonopd** [comment]
No I don't have librtlsdr installed on the system. I am using a Xubuntu bionic Live ISO.

**Comment by mryndzionek** [comment]
I've added a commit that might fix the problem: https://github.com/mryndzionek/composable-sdr/commit/b0d492a4ae00096809531e8df7b443e4edf99acc
Also triggered a new build: https://github.com/mryndzionek/composable-sdr/actions/runs/150640112
